### ISSUE TITLE
[설계] 기능명세서 작성

### ISSUE THREAD

**Issue by Lai-khan** [HICC-Bootcamp/2022-1-Happiness-Moneybox#1]
서비스의 기능에 대해 설명하는 문서를 작성한다.

## 상세
- 필수 기능과 선택 기능을 분리해서 정리해주세요.
- 서비스가 **어떤 기능**을 가지고 있는지, 각기 **어떻게 동작**하는지 사용자 관점에서 정리하면 됩니다.
   - 서비스가 간단하다면 그냥 짧게 전체적인 기능을 정리해놓는 것도 좋지만, 개발과정에서 모호함 때문에 논쟁이 생길 수 있으므로 개발 전에 세세히 정할 수 있는 부분에 대해서는 정해 놓는 것이 좋습니다.

[참고](https://mklab-co.medium.com/%EC%9E%91%EC%84%B1%EB%B2%95-%ED%99%94%EB%A9%B4%EC%84%A4%EA%B3%84%EC%84%9C-wireframe-%EC%99%80-%EA%B8%B0%EB%8A%A5%EB%AA%85%EC%84%B8%EC%84%9C-functional-specification-bbcff0071ea2)하세요. 꼭 그대로 따라하지 않아도 됩니다.

## 방법
Wiki에 기능명세서 페이지를 만들고 정리한 후, 본 이슈에 코멘트 달아주면 됩니다.

**Comment by Lai-khan** [comment]
## 예시
#### 회원가입 기능
- 닉네임과 비밀번호를 입력할 수 있다.
- 닉네임은 영어만 가능하며, 중복닉네임이 아닌지 확인할 수 있는 버튼이 옆에 있다.
- 버튼 클릭 시, 중복 닉네임 여부가 뜨며, 이를 확인해야만 회원가입을 할 수 있다. 확인하지 않고 회원가입 버튼을 누르면 “닉네임이 중복인지 확인해주십시오.”란 문구가 뜬다.
- 비밀번호는 8자리 이상이어야 하며 알파벳과 숫자의 조합이어야 한다. (FE검사)
- 모든 조건을 만족한 뒤 회원가입 버튼을 누르면 응답에 따라 성공 여부가 화면에 뜬다. 실패시 새로고침. 성공시 메인화면으로 이동한다.

어디까지나 제가 즉석에서 임시로 작성한 것이니 그대로 따라하실 필요는 없습니다. 참고만 하세요. 너무 세세하다 느껴지면 좀 간단히 작성해도 좋아요. :)

**Comment by ChooSeoyeon** [comment]
Wiki에 기능명세서 페이지 만들고 정리 완료했습니다!

**Comment by Lai-khan** [comment]
고생하셨습니다. 아주 잘 정리하셨네요! 👍 💯 

몇가지 질문과 피드백을 드리자면,
- '비밀번호 재확인'은 input 추가하고 fe에서 be로 요청 넣기 전에 두개 값이 같은가 확인만 하면 되는건데, 필수로 넣는 것은 어떨까요? 비밀번호를 실수로 잘못 입력한 것을 인지하지 못하고 회원가입 후 로그인 하지 못하는 문제를 방지할 수 있어서요.
- '회원가입' 성공시 로그인 화면으로 이동하지 않나요?
- 혹시 '글 삭제' 전에 한번 더 확인하는 절차가 있나요?
- 선택 기능 중에 추가로 구현하게 되면 DB 구조가 달라질 수 있는 기능들이 보이네요. 이 부분을 염두에 두고 DB를 설계하는 것이 좋겠어요.

참고만 하시고 굳이 수정하지 않아도 됩니다. :) 이슈 닫으셔도 됩니다.

**Comment by ChooSeoyeon** [comment]
상세한 피드백 감사합니다! 참고하겠습니다. 비밀번호 재확인과 삭제 전 확인 절차는 생각 못했었네요! DB 설계도 유의하겠습니다:)
