### ISSUE TITLE
[설계] DB 설계

### ISSUE THREAD

**Issue by Lai-khan** [HICC-Bootcamp/2022-1-Happiness-Moneybox#2]
서비스의 요구사항에 맞게 DB를 설계해보자.

## 상세
- 어떤 DBMS를 사용할 것이냐에 따라 설계방식이 조금 다릅니다만, RDB 방식을 따라가도 문제는 없습니다.
- RDB를 사용한다면 표로 테이블 구조를 그리고, 각 칼럼 이름과 데이터 타입, 제약, 테이블 간의 관계를 작성하면 되고,
- NoSQL을 사용한다면 기능 요구사항에 따라 도큐먼트와 컬렉션을 설계하면 됩니다.
- NoSQL이라고 특별히 다르게 설계해야하는 것은 아니니, ERD를 사용해 설계해도 상관없습니다.
- 중요한 것은 개발할 때 데이터를 어떻게 저장할 것인지를 미리 정해놓고 들어가는 것입니다.

[좋은 글](https://meetup.toast.com/posts/276)이 있어서 하나 첨부합니다. 참고하세요~ :)  (내용이 어렵다면 그냥 맞는 방식으로 설계해도 됩니다.)

## 방법
Wiki 페이지에 'DB 설계' 페이지 생성해서 작성한 뒤 본 이슈에 코멘트로 링크 달면 됩니다.

**Comment by ChooSeoyeon** [comment]
Wiki에 DB 설계 페이지 생성해서 작성 완료했습니다!

**Comment by Lai-khan** [comment]
- 몽고디비는 NoSQL로 스키마가 없기 때문에 테이블간의 관계도 없고 따로 PK를 지정할 필요 없이 `_id`가 그 역할을 대신합니다. 또한 스키마가 없어 필드의 추가와 삭제가 자유롭기 때문에 개발할 때 데이터 정합성이 깨지지 않도록 주의해야 합니다. 지금 설계는 RDB와 같이 하긴했는데 개발로 들어가게 되면 DBMS가 해당 제약사항들을 보장해 주지 않기 때문에 주의해야 합니다. 코드레벨에서 데이터가 중복되거나 정합성이 깨지지 않도록 유의해주세요.
- 따로 PK의 개념은 없지만 RDB의 관점에서 한가지 피드백을 드리자면 PK는 데이터를 식별할 수 있는 최소한의 키 조합으로 회원 테이블에서는 `userId`가 그 역할을 하고 있습니다. 회원가입을 할때 중복을 검사하기 때문에 고유함이 보장되지만 nickname은 아무런 검사를 하지 않기 때문에 보장되지 않습니다. 물론 id와 같이 묶으면 식별할 수 있는 키 조합이 되겠지만 1개로도 식별할 수 있다면 굳이 2개의 키 조합을 사용할 필요는 없습니다. 그리고 주로 테이블을 조회할 때 사용할 데이터도 아마 userId일 것입니다. 그래서 이런 상황에서 PK를 지정한다면 `userId` 하나로 하는 것이 바람직해 보이네요. 몽고디비는 PK가 없으니 그냥 읽고 넘기세요. :)  다만 테이블 설계 표는 좀 수정해도 좋을 것 같네요. 개발할때는 설계를 보고 참고할테니 말이죠. PK는 없더라도 not null 같은거는 봤을 때 insert 시 해당 데이터가 빠지면 안된다는 걸 알 수 있으니까요.
- 관계랑 다른 테이블과 어떤 관계냐를 나타내는 것인데 칼럼에 대한 설명만 적혀있네요. 상단의 항목 이름을 바꾸는게 좋을 것 같습니다.

**Comment by ChooSeoyeon** [comment]
자세한 피드백 감사합니다!
- 개발 시, 데이터 정합성 깨지지 않도록 주의하겠습니다!
- PK에 대한 내용이 헷갈렸는데 이해됐습니다! nickname을 PK에서 not null로 수정 완료했습니다.
- 상단 항목 이름을 관계에서 설명으로 수정했습니다.
