### ISSUE TITLE
[설계] API 설계

### ISSUE THREAD

**Issue by Lai-khan** [HICC-Bootcamp/2022-1-Happiness-Moneybox#3]
'이렇게 HTTP 요청을 보내면, 이렇게 응답해준다'라는 스펙을 기능에 따라 설계한다.
HTTP에 대한 이해 필요

## 상세
들어가야할 내용은 다음과 같습니다.
- HTTP Method
- URL
- Request Format
- Response Format

## 참고
- [REST API 설계 가이드](https://sharplee7.tistory.com/49)
- [Rest API Naming Guide](https://restfulapi.net/resource-naming/)

첨부한 링크는 다 REST API에 관한 링크긴 한데, 꼭 Restful하게 작성하지 않아도 됩니다. 우선 처음이니까 기본적인 HTTP API 형식에만 부합해도 됩니다.

## 방법
Wiki 페이지에 'API 설계' 페이지 생성해서 작성한 뒤 본 이슈에 코멘트로 링크 달면 됩니다.

**Comment by Lai-khan** [comment]
## 예시
### 회원 목록
```
GET /users
```
### Request Data
없음

### Response Data
```
[
    {
        "userId": 사용자 ID, (string)
        "userName": 사용자 이름, (string)
        "userProfileUrl": 사용자 프로필 사진 Url (string)
    },
    . . . . . .
]
```
```
[
    {
        "userId": "user12345",
        "userName": "람보",
        "userProfileUrl": "https://item.kakaocdn.net/do/33702f467a63bf8b9eb32adb9f539fd6617ea012db208c18f6e83b1a90a7baa7",
    },
    {
        "userId": "nanananan",
        "userName": "무무",
        "userProfileUrl": "https://item.kakaocdn.net/do/33702f467a63bf8b9eb32adb9f539fd6617ea012db208c18f6e83b1a90a7baa7",
    },
    {
        "userId": "yeah44",
        "userName": "크롱",
        "userProfileUrl": "https://item.kakaocdn.net/do/33702f467a63bf8b9eb32adb9f539fd6617ea012db208c18f6e83b1a90a7baa7",
    },
]
```

**Comment by ChooSeoyeon** [comment]
Wiki에 API 설계 페이지 생성해서 작성 완료했습니다!

**Comment by Lai-khan** [comment]
고생하셨습니다. :clap: DB보다 API를 먼저 하셨네요.ㅎㅎ

피드백을 드리자면,
- userID → userId. camelCase를 따르는 것이 좋습니다.
- pwdchk → 이렇게 줄여서 쓰는 것은 길이를 줄여줄지는 모르나 가독성은 좋지 않습니다. passwordCheck으로 바꾸는 게 좋아보이네요.
- URL 주소는 언더바(_) 대신 하이픈(-)을 사용하는게 규칙입니다. 그리고 가급적이면 불가피한 경우를 제외하고는 사용하지 않는게 좋습니다.
- id 앞에 하이픈(_)은 왜 붙었나요?
- 글 작성할 때 글 번호가 이미 생성되어 있는 것은 이상해보입니다. DB에서 PK로 쓰이는 데이터인것 같은데, 만약 DB에 저장할때 이미 해당 id를 가진 데이터가 있으면 어떻게 할건가요? (DB 동시성 참고.)
- `이전 연도 저금통 모음`은 그냥 count만 내려보내는 건가요? 그렇다면 URL에 count가 들어가는 것이 더 명확하게 의미를 표현할 수 있을 것 같네요. 그리고 `previous`는 형용사라 자원을 나타내기에 적합하지 않습니다. 예전 기록을 나타내고 싶다면 `record`나 `history`같이 명사로 표현하는 것이 좋겠네요.
- `이전 연도 글 목록 조회`와 `이전 연도 글 조회`는 API 형식이나 데이터가 그냥 `글목록`, `글조회`랑 똑같아서 그냥 해당 API에 날짜 파라미터만 옵션으로 넣어서 그대로 써도 되겠네요. 날짜만 다를 뿐 화면이 달라진다고 글을 가져오는 해당 API의 기능이 달라진 것은 아니니 굳이 URL을 바꿔서 새로 만들 필요는 없어보입니다. 어차피 내부 구현은 거의 같을 거에요. 위의 count도 그냥 previous를 빼는게 좋겠네요.
- 그리고 `이전 연도 글 조회`에서 year 같이 자원을 식별하는 데이터가 아니라 필터링에 쓰이는 데이터는 query parameter로 나타내는 것이 좋습니다.

**Comment by ChooSeoyeon** [comment]
좋은 피드백 감사합니다!!
- userId, passwordCheck 그리고 URL 주소(하이픈 사용하도록) 수정 완료했습니다.
- _id는 제가 따로 만들어 낸 key가 아니라 mongoDB에서 모든 데이터들에게 자동으로 부여되는 key인 ObjectId이기에 부여된 명칭 그대로 _id라 썼습니다!
- 글 삭제, 수정 등을 위해 글 작성 시 유니크한 _id 값(글 번호)을 함께 넣어줬습니다. DB에서 PK로 쓰이는 데이터 맞습니다! Auto Increment기능을 직접 구현하기 위해, 지금까지 발행한 '총 게시물 개수'를 별도의 collection에 기록해두고 이 값을 _id의 값으로 넣어줌으로써 글을 하나 발행할 때마다 유니크한 _id가 부여되게 하려 합니다. 이때, '총 게시물 개수'는 글을 발행할 때마다 1씩 증가하고 글 삭제의 영향을 받지 않게 만들 예정입니다. 예를 들어 1부터 100까지의 _id 값을 가진 글들이 있는데 50~100까지 삭제하면 새로 작성한 글의 _id 값이 101이 되게 하려 합니다. 제가 생각했던 바를 코드로 표현하자면 아래와 같을 것 같습니다! 혹시 제가 잘못 알고 있는 부분이나 더 좋은 방법이 있을까요??
```
app.post('/posts', function(req, res){
    res.send('전송완료');
    db.collection('counter').findOne({name: '게시물개수'}, function(error, result){
        var 총게시물개수 = result.totalPost;
        db.collection('post').insertOne({_id: 총게시물개수+1, 제목: req.body.title, 날짜: req.body.date}, function(){
            db.collection('counter').updateOne({name: '게시물개수'}, { $inc : {totalPost:1} }, function(){
             });
        });
    });
});
```
-  previous는 명사 history로 수정했습니다!  `이전 연도 저금통 모음`은 사용자가 클릭하면 해당 년도의 글 목록으로 이동할 수 있는 버튼들이 나열되어 있는 페이지입니다.  버튼을 몇 개 만들지는 이전 연도 저금통 개수(count)에 따라 달라질 거 같아 count를 내보내게 설계했습니다. URL에 count가 들어가는 것은 query parameter로 나타내면 되려나요? query parameter로 url설계 시 `/history?count=`이라고 쓰는 게 맞을까요??
- `이전 연도 글 목록 조회`와 `이전 연도 글 조회`는 없앴습니다. 이를 대신해 `글 목록 조회`와 `글 조회` api에 날짜 파라미터를 옵션으로 넣어서 쓰려면 url에 query parameter로 넣으면 되는 건가요?? 그럼 '글 목록 조회'는 `GET /posts?date=`으로, '글 조회'는 `GET /posts/:id?date='으로 수정하면 되는건가요? 이런 식으로 path variable과 query parameter를 같이 사용하는 게 불가능하다면 `글 조회`는 어떻게 수정해야 할까요??
읽어주셔서 감사합니다:)

**Comment by Lai-khan** [comment]
- DB에 저장되는 데이터명 규칙과 JSON으로 주고받는 데이터명의 규칙은 다릅니다. _id라고 DB에서는 저장되더라도 주고받을때는 네이밍 규칙을 통일하는 것이 좋습니다.
- 글 삭제, 수정에 id 값이 필요한 것은 맞습니다. 하지만 글을 생성할 때 필요하지는 않습니다. 제 말은 글을 생성할때 서버로 보내는 데이터에 DB에 저장할때 자동으로 생성되게 할 수 있는 id값이 들어있다는 것입니다.
- Auto Increment 기능을 왜 직접 구현하려고 하나요? DBMS에서 지원하지 않나요?
- > 위의 count도 그냥 previous를 빼는게 좋겠네요.
   - previous를 history로 수정하라는 것은 URL에 형용사가 아닌 명사를 사용하라는 의미였습니다. 서비스 기능과 필요한 API들을 보면 `글 목록 조회`와 `글 조회`가 `이전연도 글목록 조회`와 `이전연도 글 조회`와 별반 다르지 않다는 것을 알 수 있습니다. 그러면 굳이 API를 이전연도 용으로 분리할 이유가 없다는 것입니다. 또한 API가 전달하고자 하는 데이터는 **저금통의 개수**인데, URL이 `/history`면 이를 정확히 나타내지 못합니다. 그냥 `/count` 또는 좀 더 정확히 나타내고자 한다면 `/posts/count` 정도가 좋겠네요. :) (참고: [REST API URL 규칙](https://velog.io/@pjh612/REST-API-URI-%EA%B7%9C%EC%B9%99))
- path variable과 query parameter는 같이 사용할 수 있습니다. Method가 GET이면 Request Data의 데이터가 queryString으로 전달되고 POST 면 HTTP Body로 전달됩니다. (물론 경우에 따라 둘을 적절히 섞어 사용할 수는 있습니다.) 그러니 글 목록 조회 API Request Data에 date를 넣어주면 됩니다. 좀 더 의미를 정확히 하려면 year나 startDate&endDate가 되겠지만요.

**Comment by ChooSeoyeon** [comment]
친절한 답변 감사합니다!
- 네이밍 규칙 통일되도록 _id를 id로 수정했습니다. JSON이 무엇인지 잘 몰랐는데 이 기회에 알게 되었습니다!
- `글 작성`의 request data에서 id값 없앴습니다.
-  MongoDB는 Auto Increment 기능 제공하지 않는 걸로 알고 있습니다! 허나 더 찾아보니 Mongoose-auto-increment와 같은 라이브러리 이용하면 되는 것 같습니다.
- `/history`를 `/posts/count`로 수정했습니다. 굳이 API를 이전 연도 용으로 분리할 필요 없다는 점 이해됐습니다!
- `글 목록 조회`와 `글 조회`의 Request Data에 year 넣어줌으로써 연도 구분 할 수 있게 수정했습니다. 둘다 Method가 GET이라 멘토님 말씀대로 Request Data의 데이터를 queryString으로 전달하면 될 것 같습니다!

API 설계가 익숙하지 않아 부족한 부분이 많습니다. 도움 주셔서 감사합니다!

**Comment by Lai-khan** [comment]
고생하셨습니다. 👏 이슈 닫으셔도 됩니다.
